### ISSUE TITLE
Looks like Mint changed their login process

### ISSUE THREAD

**Issue by jamiew** [toddmazierski/mint-exporter#17]
Thanks for this tool first of all. 

I caught a 301 Redirect error in my mint-exporter logs recently – looks like the login URL has changed from https://www.mint.com to https://mint.intuit.com (great), but is followed quickly by another redirect... so some work to do here

Happy to help debug further, just wanted to file and see if anyone else was tackling already

**Comment by toddmazierski** [comment]
Thanks for the report, @jamiew!

Unfortunately, since June this library (and many other Mint libraries) are no longer able to authenticate, please see [this comment](https://github.com/toddmazierski/mint-exporter/issues/16#issuecomment-225373749) for more information.

**Comment by jamiew** [comment]
Figured it was a known issue, thanks for letting me know. Will check out the getaccounts-Casper project you mentioned
